import { jsPDF } from "jspdf";

import { PurchaseOrder } from "@/types/purchase";
import { formatOrderDate, formatOrderPrice } from "@/utils/purchaseOrder";

const MARGIN = 20;
const LINE_HEIGHT = 10;
const SECOND_COLUMN_X = 100;

export const exportPurchaseOrderPDF = (order: PurchaseOrder): void => {
  const doc = new jsPDF();
  let currentY = MARGIN;

  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("PURCHASE ORDER", MARGIN, currentY);
  currentY += LINE_HEIGHT * 2;

  doc.setFontSize(16);
  doc.text("Order Summary", MARGIN, currentY);
  currentY += LINE_HEIGHT;
  doc.setLineWidth(0.5);
  doc.line(MARGIN, currentY, 190, currentY);
  currentY += LINE_HEIGHT;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");

  const orderId = order._id;
  const shortId = orderId.slice(-8).toUpperCase();

  const details = [
    { label: "PO Reference:", value: `#${shortId}` },
    { label: "Full ID:", value: orderId },
    { label: "Status:", value: order.status.toUpperCase() },
    { label: "Order Date:", value: formatOrderDate(order.createdAt) },
  ];

  details.forEach(detail => {
    doc.setFont("helvetica", "bold");
    doc.text(detail.label, MARGIN, currentY);
    doc.setFont("helvetica", "normal");
    doc.text(String(detail.value), SECOND_COLUMN_X, currentY);
    currentY += LINE_HEIGHT;
  });

  currentY += LINE_HEIGHT;

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Motorcycle Details", MARGIN, currentY);
  currentY += LINE_HEIGHT;
  doc.setLineWidth(0.5);
  doc.line(MARGIN, currentY, 190, currentY);
  currentY += LINE_HEIGHT;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");

  const inventory = order.inventoryId;
  const motorcycleDetails = [
    { label: "Brand:", value: inventory?.brand || "N/A" },
    { label: "Model:", value: inventory?.model || "N/A" },
    { label: "Year:", value: inventory?.year || "N/A" },
    {
      label: "Engine:",
      value: inventory?.engineCapacity ? `${inventory.engineCapacity}cc` : "N/A",
    },
    {
      label: "Condition:",
      value: inventory?.condition
        ? inventory.condition.charAt(0).toUpperCase() + inventory.condition.slice(1)
        : "N/A",
    },
    { label: "Color:", value: inventory?.color || "N/A" },
  ];

  motorcycleDetails.forEach(detail => {
    doc.setFont("helvetica", "bold");
    doc.text(detail.label, MARGIN, currentY);
    doc.setFont("helvetica", "normal");
    doc.text(String(detail.value), SECOND_COLUMN_X, currentY);
    currentY += LINE_HEIGHT;
  });

  currentY += LINE_HEIGHT;

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Payment & Parties", MARGIN, currentY);
  currentY += LINE_HEIGHT;
  doc.setLineWidth(0.5);
  doc.line(MARGIN, currentY, 190, currentY);
  currentY += LINE_HEIGHT;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");

  const paymentDetails = [
    {
      label: "Buyer Name:",
      value: order.customerName
        ? order.customerName.charAt(0).toUpperCase() + order.customerName.slice(1)
        : "N/A",
    },
    { label: "Seller ID:", value: inventory?.userId || "N/A" },
    { label: "Quantity:", value: String(order.quantityPurchased) },
    {
      label: "Unit Price:",
      value: `$${formatOrderPrice(order.totalPrice / order.quantityPurchased)}`,
    },
    { label: "Total Amount:", value: `$${formatOrderPrice(order.totalPrice)}` },
  ];

  paymentDetails.forEach(detail => {
    doc.setFont("helvetica", "bold");
    doc.text(detail.label, MARGIN, currentY);
    doc.setFont("helvetica", "normal");
    doc.text(String(detail.value), SECOND_COLUMN_X, currentY);
    currentY += LINE_HEIGHT;
  });

  currentY = 280;
  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text("Generated by NextJS Task Manager - Professional Order Tracking", MARGIN, currentY);

  doc.save(`PO-${shortId}.pdf`);
};
