import { Inventory } from "./types";

const inventories: Inventory[] = [
  {
    id: '1',
    brand: 'Honda',
    model: 'CBR500R',
    year: 2024,
    type: 'sport',
    engineCapacity: 471,
    color: 'Grand Prix Red',
    price: 6999,
    quantity: 5,
    condition: 'new',
    features: ['ABS', 'LED Headlights', 'Digital Display'],
    inStock: true,
  },
  {
    id: '2',
    brand: 'Yamaha',
    model: 'MT-07',
    year: 2024,
    type: 'naked',
    engineCapacity: 689,
    color: 'Cyan Storm',
    price: 7899,
    quantity: 3,
    condition: 'new',
    features: ['ABS', 'Traction Control', 'Quickshifter'],
    inStock: true,
  },
  {
    id: '3',
    brand: 'Kawasaki',
    model: 'Ninja 400',
    year: 2023,
    type: 'sport',
    engineCapacity: 399,
    color: 'Lime Green',
    price: 5499,
    quantity: 2,
    condition: 'used',
    features: ['ABS', 'Slipper Clutch', 'Digital Display'],
    inStock: true,
  },
  {
    id: '4',
    brand: 'Royal Enfield',
    model: 'Himalayan',
    year: 2024,
    type: 'adventure',
    engineCapacity: 411,
    color: 'Granite Black',
    price: 4999,
    quantity: 8,
    condition: 'new',
    features: ['ABS', 'Long Travel Suspension', 'Windscreen'],
    inStock: true,
  },
  {
    id: '5',
    brand: 'Harley-Davidson',
    model: 'Street 750',
    year: 2023,
    type: 'cruiser',
    engineCapacity: 749,
    color: 'Vivid Black',
    price: 7499,
    quantity: 0,
    condition: 'new',
    features: ['ABS', 'Low Seat Height', 'Chrome Finish'],
    inStock: false,
  },
  {
    id: '6',
    brand: 'Suzuki',
    model: 'V-Strom 650',
    year: 2024,
    type: 'adventure',
    engineCapacity: 645,
    color: 'Champion Yellow',
    price: 8799,
    quantity: 4,
    condition: 'new',
    features: ['ABS', 'Traction Control', 'Cruise Control', 'LED Lighting'],
    inStock: true,
  },
  {
    id: '7',
    brand: 'Honda',
    model: 'CBR500R',
    year: 2023,
    type: 'sport',
    engineCapacity: 471,
    color: 'Pearl White',
    price: 6499,
    quantity: 3,
    condition: 'used',
    features: ['ABS', 'LED Headlights', 'Digital Display'],
    inStock: true,
  },
  {
    id: '8',
    brand: 'Honda',
    model: 'CBR500R',
    year: 2024,
    type: 'sport',
    engineCapacity: 471,
    color: 'Matte Black',
    price: 7199,
    quantity: 7,
    condition: 'new',
    features: ['ABS', 'LED Headlights', 'Digital Display', 'USB Charging'],
    inStock: true,
  },
  {
    id: '9',
    brand: 'Honda',
    model: 'CBR500R',
    year: 2022,
    type: 'sport',
    engineCapacity: 471,
    color: 'Grand Prix Red',
    price: 5999,
    quantity: 2,
    condition: 'used',
    features: ['ABS', 'LED Headlights'],
    inStock: true,
  },
  {
    id: '10',
    brand: 'Yamaha',
    model: 'MT-07',
    year: 2023,
    type: 'naked',
    engineCapacity: 689,
    color: 'Tech Black',
    price: 7399,
    quantity: 4,
    condition: 'used',
    features: ['ABS', 'Traction Control'],
    inStock: true,
  },
  {
    id: '11',
    brand: 'Yamaha',
    model: 'MT-07',
    year: 2024,
    type: 'naked',
    engineCapacity: 689,
    color: 'Ice Fluo',
    price: 8099,
    quantity: 6,
    condition: 'new',
    features: ['ABS', 'Traction Control', 'Quickshifter', 'TFT Display'],
    inStock: true,
  },
  {
    id: '12',
    brand: 'Yamaha',
    model: 'MT-07',
    year: 2025,
    type: 'naked',
    engineCapacity: 689,
    color: 'Raven',
    price: 8299,
    quantity: 0,
    condition: 'new',
    features: ['ABS', 'Traction Control', 'Quickshifter', 'TFT Display', 'Ride Modes'],
    inStock: false,
  },
  {
    id: '13',
    brand: 'Kawasaki',
    model: 'Ninja 400',
    year: 2024,
    type: 'sport',
    engineCapacity: 399,
    color: 'Metallic Spark Black',
    price: 5999,
    quantity: 5,
    condition: 'new',
    features: ['ABS', 'Slipper Clutch', 'Digital Display', 'LED Lighting'],
    inStock: true,
  },
  {
    id: '14',
    brand: 'Kawasaki',
    model: 'Ninja 400',
    year: 2023,
    type: 'sport',
    engineCapacity: 399,
    color: 'Pearl White',
    price: 5299,
    quantity: 3,
    condition: 'used',
    features: ['ABS', 'Slipper Clutch', 'Digital Display'],
    inStock: true,
  },
  {
    id: '15',
    brand: 'Kawasaki',
    model: 'Ninja 400',
    year: 2024,
    type: 'sport',
    engineCapacity: 399,
    color: 'Lime Green',
    price: 6199,
    quantity: 8,
    condition: 'new',
    features: ['ABS', 'Slipper Clutch', 'Digital Display', 'LED Lighting'],
    inStock: true,
  },
  {
    id: '16',
    brand: 'Royal Enfield',
    model: 'Himalayan',
    year: 2023,
    type: 'adventure',
    engineCapacity: 411,
    color: 'Lake Blue',
    price: 4699,
    quantity: 4,
    condition: 'used',
    features: ['ABS', 'Long Travel Suspension'],
    inStock: true,
  },
  {
    id: '17',
    brand: 'Royal Enfield',
    model: 'Himalayan',
    year: 2024,
    type: 'adventure',
    engineCapacity: 411,
    color: 'Snow White',
    price: 5099,
    quantity: 6,
    condition: 'new',
    features: ['ABS', 'Long Travel Suspension', 'Windscreen', 'Panniers'],
    inStock: true,
  },
  {
    id: '18',
    brand: 'Royal Enfield',
    model: 'Himalayan',
    year: 2024,
    type: 'adventure',
    engineCapacity: 411,
    color: 'Mirage Silver',
    price: 5199,
    quantity: 5,
    condition: 'new',
    features: ['ABS', 'Long Travel Suspension', 'Windscreen', 'Navigation Mount'],
    inStock: true,
  },
  {
    id: '19',
    brand: 'Harley-Davidson',
    model: 'Street 750',
    year: 2024,
    type: 'cruiser',
    engineCapacity: 749,
    color: 'Billiard Red',
    price: 7799,
    quantity: 2,
    condition: 'new',
    features: ['ABS', 'Low Seat Height', 'Chrome Finish', 'Custom Exhaust'],
    inStock: true,
  },
  {
    id: '20',
    brand: 'Harley-Davidson',
    model: 'Street 750',
    year: 2022,
    type: 'cruiser',
    engineCapacity: 749,
    color: 'Vivid Black',
    price: 6999,
    quantity: 1,
    condition: 'used',
    features: ['ABS', 'Low Seat Height', 'Chrome Finish'],
    inStock: true,
  },
  {
    id: '21',
    brand: 'Suzuki',
    model: 'V-Strom 650',
    year: 2023,
    type: 'adventure',
    engineCapacity: 645,
    color: 'Pearl Brilliant White',
    price: 8299,
    quantity: 3,
    condition: 'used',
    features: ['ABS', 'Traction Control', 'LED Lighting'],
    inStock: true,
  },
  {
    id: '22',
    brand: 'Suzuki',
    model: 'V-Strom 650',
    year: 2024,
    type: 'adventure',
    engineCapacity: 645,
    color: 'Glass Sparkle Black',
    price: 8999,
    quantity: 5,
    condition: 'new',
    features: ['ABS', 'Traction Control', 'Cruise Control', 'LED Lighting', 'Heated Grips'],
    inStock: true,
  },
  {
    id: '23',
    brand: 'KTM',
    model: 'Duke 390',
    year: 2024,
    type: 'naked',
    engineCapacity: 373,
    color: 'Orange',
    price: 5799,
    quantity: 10,
    condition: 'new',
    features: ['ABS', 'Ride by Wire', 'TFT Display', 'LED Lighting'],
    inStock: true,
  },
  {
    id: '24',
    brand: 'KTM',
    model: 'Duke 390',
    year: 2023,
    type: 'naked',
    engineCapacity: 373,
    color: 'White',
    price: 5299,
    quantity: 3,
    condition: 'used',
    features: ['ABS', 'Ride by Wire', 'TFT Display'],
    inStock: true,
  },
  {
    id: '25',
    brand: 'KTM',
    model: 'Duke 390',
    year: 2024,
    type: 'naked',
    engineCapacity: 373,
    color: 'Black',
    price: 5899,
    quantity: 7,
    condition: 'new',
    features: ['ABS', 'Ride by Wire', 'TFT Display', 'LED Lighting', 'Quickshifter'],
    inStock: true,
  },
  {
    id: '26',
    brand: 'BMW',
    model: 'G 310 R',
    year: 2024,
    type: 'naked',
    engineCapacity: 313,
    color: 'Racing Red',
    price: 4999,
    quantity: 4,
    condition: 'new',
    features: ['ABS', 'LED Headlights', 'Digital Display'],
    inStock: true,
  },
  {
    id: '27',
    brand: 'BMW',
    model: 'G 310 R',
    year: 2023,
    type: 'naked',
    engineCapacity: 313,
    color: 'Cosmic Black',
    price: 4599,
    quantity: 2,
    condition: 'used',
    features: ['ABS', 'LED Headlights'],
    inStock: true,
  },
  {
    id: '28',
    brand: 'BMW',
    model: 'G 310 R',
    year: 2024,
    type: 'naked',
    engineCapacity: 313,
    color: 'Polar White',
    price: 5099,
    quantity: 6,
    condition: 'new',
    features: ['ABS', 'LED Headlights', 'Digital Display', 'USB Charging'],
    inStock: true,
  },
  {
    id: '29',
    brand: 'Triumph',
    model: 'Street Triple',
    year: 2024,
    type: 'naked',
    engineCapacity: 765,
    color: 'Matt Jet Black',
    price: 10499,
    quantity: 2,
    condition: 'new',
    features: ['ABS', 'Traction Control', 'TFT Display', 'Ride Modes', 'Quickshifter'],
    inStock: true,
  },
  {
    id: '30',
    brand: 'Triumph',
    model: 'Street Triple',
    year: 2023,
    type: 'naked',
    engineCapacity: 765,
    color: 'Sapphire Black',
    price: 9899,
    quantity: 1,
    condition: 'used',
    features: ['ABS', 'Traction Control', 'TFT Display', 'Ride Modes'],
    inStock: true,
  },
  {
    id: '31',
    brand: 'Triumph',
    model: 'Street Triple',
    year: 2024,
    type: 'naked',
    engineCapacity: 765,
    color: 'Carnival Red',
    price: 10699,
    quantity: 3,
    condition: 'new',
    features: ['ABS', 'Traction Control', 'TFT Display', 'Ride Modes', 'Quickshifter', 'Brembo Brakes'],
    inStock: true,
  },
  {
    id: '32',
    brand: 'Ducati',
    model: 'Monster 821',
    year: 2024,
    type: 'naked',
    engineCapacity: 821,
    color: 'Ducati Red',
    price: 11999,
    quantity: 2,
    condition: 'new',
    features: ['ABS', 'Traction Control', 'TFT Display', 'Ride Modes', 'LED Lighting'],
    inStock: true,
  },
  {
    id: '33',
    brand: 'Ducati',
    model: 'Monster 821',
    year: 2023,
    type: 'naked',
    engineCapacity: 821,
    color: 'Dark Stealth',
    price: 11299,
    quantity: 1,
    condition: 'used',
    features: ['ABS', 'Traction Control', 'TFT Display', 'Ride Modes'],
    inStock: true,
  },
  {
    id: '34',
    brand: 'Ducati',
    model: 'Monster 821',
    year: 2024,
    type: 'naked',
    engineCapacity: 821,
    color: 'Star White Silk',
    price: 12199,
    quantity: 0,
    condition: 'new',
    features: ['ABS', 'Traction Control', 'TFT Display', 'Ride Modes', 'LED Lighting', 'Quickshifter'],
    inStock: false,
  },
  {
    id: '35',
    brand: 'Honda',
    model: 'CB650R',
    year: 2024,
    type: 'naked',
    engineCapacity: 649,
    color: 'Gunpowder Black Metallic',
    price: 8799,
    quantity: 4,
    condition: 'new',
    features: ['ABS', 'LED Lighting', 'Showa Suspension', 'Digital Display'],
    inStock: true,
  },
  {
    id: '36',
    brand: 'Honda',
    model: 'CB650R',
    year: 2023,
    type: 'naked',
    engineCapacity: 649,
    color: 'Pearl Smoky Gray',
    price: 8299,
    quantity: 2,
    condition: 'used',
    features: ['ABS', 'LED Lighting', 'Showa Suspension'],
    inStock: true,
  },
  {
    id: '37',
    brand: 'Honda',
    model: 'CB650R',
    year: 2024,
    type: 'naked',
    engineCapacity: 649,
    color: 'Candy Chromosphere Red',
    price: 8999,
    quantity: 5,
    condition: 'new',
    features: ['ABS', 'LED Lighting', 'Showa Suspension', 'Digital Display', 'Quickshifter'],
    inStock: true,
  },
  {
    id: '38',
    brand: 'Yamaha',
    model: 'R3',
    year: 2024,
    type: 'sport',
    engineCapacity: 321,
    color: 'Yamaha Blue',
    price: 5299,
    quantity: 8,
    condition: 'new',
    features: ['ABS', 'Slipper Clutch', 'LED Lighting', 'Digital Display'],
    inStock: true,
  },
  {
    id: '39',
    brand: 'Yamaha',
    model: 'R3',
    year: 2023,
    type: 'sport',
    engineCapacity: 321,
    color: 'Matte Black',
    price: 4899,
    quantity: 4,
    condition: 'used',
    features: ['ABS', 'Slipper Clutch', 'LED Lighting'],
    inStock: true,
  },
  {
    id: '40',
    brand: 'Yamaha',
    model: 'R3',
    year: 2024,
    type: 'sport',
    engineCapacity: 321,
    color: 'Icon Blue',
    price: 5499,
    quantity: 6,
    condition: 'new',
    features: ['ABS', 'Slipper Clutch', 'LED Lighting', 'Digital Display', 'Race Graphics'],
    inStock: true,
  },
  {
    id: '41',
    brand: 'Kawasaki',
    model: 'Z650',
    year: 2024,
    type: 'naked',
    engineCapacity: 649,
    color: 'Metallic Spark Black',
    price: 7499,
    quantity: 5,
    condition: 'new',
    features: ['ABS', 'Traction Control', 'LED Lighting', 'TFT Display'],
    inStock: true,
  },
  {
    id: '42',
    brand: 'Kawasaki',
    model: 'Z650',
    year: 2023,
    type: 'naked',
    engineCapacity: 649,
    color: 'Candy Lime Green',
    price: 6999,
    quantity: 3,
    condition: 'used',
    features: ['ABS', 'LED Lighting'],
    inStock: true,
  },
  {
    id: '43',
    brand: 'Kawasaki',
    model: 'Z650',
    year: 2024,
    type: 'naked',
    engineCapacity: 649,
    color: 'Pearl Flat Stardust White',
    price: 7699,
    quantity: 7,
    condition: 'new',
    features: ['ABS', 'Traction Control', 'LED Lighting', 'TFT Display', 'Quickshifter'],
    inStock: true,
  },
  {
    id: '44',
    brand: 'Suzuki',
    model: 'GSX-S750',
    year: 2024,
    type: 'naked',
    engineCapacity: 749,
    price: 8499,
    color: 'Metallic Triton Blue',
    quantity: 3,
    condition: 'new',
    features: ['ABS', 'Traction Control', 'LED Lighting', 'Digital Display'],
    inStock: true,
  },
  {
    id: '45',
    brand: 'Suzuki',
    model: 'GSX-S750',
    year: 2023,
    type: 'naked',
    engineCapacity: 749,
    color: 'Glass Sparkle Black',
    price: 7999,
    quantity: 2,
    condition: 'used',
    features: ['ABS', 'Traction Control', 'LED Lighting'],
    inStock: true,
  },
  {
    id: '46',
    brand: 'Suzuki',
    model: 'GSX-S750',
    year: 2024,
    type: 'naked',
    engineCapacity: 749,
    color: 'Pearl Brilliant White',
    price: 8699,
    quantity: 4,
    condition: 'new',
    features: ['ABS', 'Traction Control', 'LED Lighting', 'Digital Display', 'Quickshifter'],
    inStock: true,
  },
  {
    id: '47',
    brand: 'Royal Enfield',
    model: 'Classic 350',
    year: 2024,
    type: 'cruiser',
    engineCapacity: 349,
    color: 'Stealth Black',
    price: 4499,
    quantity: 12,
    condition: 'new',
    features: ['ABS', 'Retro Styling', 'Dual Channel ABS'],
    inStock: true,
  },
  {
    id: '48',
    brand: 'Royal Enfield',
    model: 'Classic 350',
    year: 2023,
    type: 'cruiser',
    engineCapacity: 349,
    color: 'Signals Airborne Blue',
    price: 4199,
    quantity: 5,
    condition: 'used',
    features: ['ABS', 'Retro Styling'],
    inStock: true,
  },
  {
    id: '49',
    brand: 'Royal Enfield',
    model: 'Classic 350',
    year: 2024,
    type: 'cruiser',
    engineCapacity: 349,
    color: 'Marsh Grey',
    price: 4599,
    quantity: 9,
    condition: 'new',
    features: ['ABS', 'Retro Styling', 'Dual Channel ABS', 'Tripper Navigation'],
    inStock: true,
  },
  {
    id: '50',
    brand: 'Honda',
    model: 'Rebel 500',
    year: 2024,
    type: 'cruiser',
    engineCapacity: 471,
    color: 'Matte Armored Silver Metallic',
    price: 6799,
    quantity: 6,
    condition: 'new',
    features: ['ABS', 'Low Seat Height', 'LED Lighting', 'Digital Display'],
    inStock: true,
  },
  {
    id: '51',
    brand: 'Honda',
    model: 'Rebel 500',
    year: 2023,
    type: 'cruiser',
    engineCapacity: 471,
    color: 'Matte Black',
    price: 6299,
    quantity: 3,
    condition: 'used',
    features: ['ABS', 'Low Seat Height', 'LED Lighting'],
    inStock: true,
  },
  {
    id: '52',
    brand: 'Honda',
    model: 'Rebel 500',
    year: 2024,
    type: 'cruiser',
    engineCapacity: 471,
    color: 'Pearl Organic Green',
    price: 6999,
    quantity: 0,
    condition: 'new',
    features: ['ABS', 'Low Seat Height', 'LED Lighting', 'Digital Display', 'USB Charging'],
    inStock: false,
  },
];

export default inventories;